### ISSUE TITLE
Guess Types sometimes causes continuous "Working..."

### ISSUE THREAD

**Issue by thadguidry** [wetneb/openrefine-wikidata#3]
Steps to reproduce with OpenRefine 2.6 RC2

When trying to reconcile on Column 1... (where 3rd row purposefully mispelled)

All|Column 1|Column 2
---|-----------|---------
1.|Journey|Ubisoft
2.|Journey|Microsoft
3.|Jouney|Infocom
4.| |

I get the below error stack trace.
Perhaps this might be due to the empty space for my 4th line where "query":"" ??

Interestingly, the 3rd row is actually showing as "q1"... look at the misspelling i purposely did "Jouney".
Yet It does not throw an error and I get returned Types for Column 2 just fine...but always an error trying to recon on Column 1

```
21:30:01.805 [                   refine] POST /command/core/guess-types-of-column (9027ms)
21:30:02.357 [                  command] Failed to guess cell types for load
{"q0":{"query":"Journey","limit":3},"q1":{"query":"Jouney","limit":3},"q2":{"query":"","limit":3}} (552ms)
java.io.IOException:
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;https://tools.wmflabs.org/openrefine-wikidata/api&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>

        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:191)
        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:89)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
...
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
...
        at java.lang.Thread.run(Unknown Source)
21:30:02.360 [                  command] Exception caught (3ms)
java.io.IOException:
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;https://tools.wmflabs.org/openrefine-wikidata/api&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>

        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:191)
        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:89)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
...
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
...
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
21:30:07.445 [           ProjectManager] Saving some modified projects ... (5085ms)
21:30:07.453 [        project_utilities] Saved project '1754850059635' (8ms)
```

**Comment by wetneb** [comment]
Thanks, yes it was a bug on my side…
